name: Eleventy Build
on: [push]
jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - run: npm install
    - run: npm test
    - name: Build
      uses: TartanLlama/actions-eleventy@v1.1
      with:
        args: --output _dist
        install_dependencies: true
